### ISSUE TITLE
[Feature]: yaml property to group task by project

### ISSUE THREAD

**Issue by dromse** [dromse/obsidian-gamified-tasks#85]
### What kind of feature do you want?

Add feature to use note like group, for example add in yaml frontmatter

```yaml
gt-group: true
# or
gt-group:
 name: Cool Project
 color: #66e2fe
 priority: 0 # highest in group list
```

Then all tasks from this note will be shown in group with name of this note.

### Additional questions

- [X] I want to work on this feature request
